# Generated by Django 4.1.5 on 2023-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0001_initial'),
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes_viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('avatar_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_episode_viewed', models.TextField(default='')),
                ('animes', models.ManyToManyField(related_name='profiles', to='animes.anime')),
                ('episodes_viewed', models.ManyToManyField(related_name='profiles_viewed', through='profiles.Episodes_viewed', to='episodes.episode')),
            ],
        ),
    ]
