# Generated by Django 4.1.5 on 2023-01-10 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episodes_viewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_episode",
                        to="episodes.episode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("avatar_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_episode_viewed", models.TextField(default="")),
                (
                    "animes",
                    models.ManyToManyField(related_name="profiles", to="animes.anime"),
                ),
                (
                    "episodes_viewed",
                    models.ManyToManyField(
                        related_name="profiles_viewed",
                        through="profiles.Episodes_viewed",
                        to="episodes.episode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="episodes_viewed",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewed_profile",
                to="profiles.profile",
            ),
        ),
    ]
