# Generated by Django 4.1.5 on 2023-01-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_episode_viewed",
            field=models.TextField(default=""),
        ),
    ]
