# Generated by Django 4.1.5 on 2023-01-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0001_initial"),
        ("profiles", "0003_alter_profile_last_episode_viewed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Animes_viewed",
            new_name="Episodes_viewed",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="animes_viewed",
        ),
        migrations.AddField(
            model_name="profile",
            name="episodes_viewed",
            field=models.ManyToManyField(
                related_name="profiles_viewed",
                through="profiles.Episodes_viewed",
                to="episodes.episode",
            ),
        ),
    ]
