# Generated by Django 4.1.5 on 2023-01-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='users',
        ),
    ]
