# Generated by Django 4.1.5 on 2023-01-08 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='animes.anime'),
        ),
    ]
