# Generated by Django 4.1.5 on 2023-01-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_alter_episode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_hd_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_sd_url',
            field=models.TextField(),
        ),
    ]
