<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-01-06 12:47
=======
# Generated by Django 4.1.5 on 2023-01-06 14:04
>>>>>>> 213326dfb70d6b370bde0111601a1637b4514e78

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("animes", "0001_initial"),
=======
        ('animes', '0001_initial'),
>>>>>>> 213326dfb70d6b370bde0111601a1637b4514e78
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="anime",
            name="name",
=======
            model_name='anime',
            name='name',
>>>>>>> 213326dfb70d6b370bde0111601a1637b4514e78
            field=models.TextField(),
        ),
    ]
