# Generated by Django 4.1.5 on 2023-01-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.TextField(default=''),
        ),
    ]
