# Generated by Django 4.1.5 on 2023-01-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_anime_description_alter_anime_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='amount_of_episodes',
            field=models.IntegerField(default=0),
        ),
    ]
